# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 493)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectSerialBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSerialBox.sizePolicy().hasHeightForWidth())
        self.selectSerialBox.setSizePolicy(sizePolicy)
        self.selectSerialBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selectSerialBox.setEditable(False)
        self.selectSerialBox.setObjectName("selectSerialBox")
        self.selectSerialBox.addItem("")
        self.verticalLayout.addWidget(self.selectSerialBox)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.SingleStepButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SingleStepButton.sizePolicy().hasHeightForWidth())
        self.SingleStepButton.setSizePolicy(sizePolicy)
        self.SingleStepButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SingleStepButton.setCheckable(True)
        self.SingleStepButton.setObjectName("SingleStepButton")
        self.verticalLayout.addWidget(self.SingleStepButton)
        self.homingButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homingButton.sizePolicy().hasHeightForWidth())
        self.homingButton.setSizePolicy(sizePolicy)
        self.homingButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homingButton.setObjectName("homingButton")
        self.verticalLayout.addWidget(self.homingButton)
        self.unlockButton = QtWidgets.QPushButton(self.centralwidget)
        self.unlockButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.unlockButton.setObjectName("unlockButton")
        self.verticalLayout.addWidget(self.unlockButton)
        self.setzeroButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setzeroButton.sizePolicy().hasHeightForWidth())
        self.setzeroButton.setSizePolicy(sizePolicy)
        self.setzeroButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setzeroButton.setObjectName("setzeroButton")
        self.verticalLayout.addWidget(self.setzeroButton)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.addposButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addposButton.sizePolicy().hasHeightForWidth())
        self.addposButton.setSizePolicy(sizePolicy)
        self.addposButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addposButton.setAutoFillBackground(False)
        self.addposButton.setObjectName("addposButton")
        self.verticalLayout.addWidget(self.addposButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ramanFilename = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramanFilename.sizePolicy().hasHeightForWidth())
        self.ramanFilename.setSizePolicy(sizePolicy)
        self.ramanFilename.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ramanFilename.setObjectName("ramanFilename")
        self.verticalLayout.addWidget(self.ramanFilename)
        self.ramanButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramanButton.sizePolicy().hasHeightForWidth())
        self.ramanButton.setSizePolicy(sizePolicy)
        self.ramanButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ramanButton.setObjectName("ramanButton")
        self.verticalLayout.addWidget(self.ramanButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.circlePointsBox = QtWidgets.QSpinBox(self.centralwidget)
        self.circlePointsBox.setMinimum(2)
        self.circlePointsBox.setObjectName("circlePointsBox")
        self.horizontalLayout_3.addWidget(self.circlePointsBox)
        self.radiusBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.radiusBox.setMinimum(0.0)
        self.radiusBox.setMaximum(5.0)
        self.radiusBox.setSingleStep(0.01)
        self.radiusBox.setProperty("value", 0.01)
        self.radiusBox.setObjectName("radiusBox")
        self.horizontalLayout_3.addWidget(self.radiusBox)
        self.addCircleButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCircleButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addCircleButton.setObjectName("addCircleButton")
        self.horizontalLayout_3.addWidget(self.addCircleButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        spacerItem = QtWidgets.QSpacerItem(0, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.StopExecutionButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.StopExecutionButton.sizePolicy().hasHeightForWidth())
        self.StopExecutionButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.StopExecutionButton.setFont(font)
        self.StopExecutionButton.setObjectName("StopExecutionButton")
        self.verticalLayout.addWidget(self.StopExecutionButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stateLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stateLabel.setFont(font)
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout.addWidget(self.stateLabel)
        self.coordinatesLCD = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinatesLCD.sizePolicy().hasHeightForWidth())
        self.coordinatesLCD.setSizePolicy(sizePolicy)
        self.coordinatesLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.coordinatesLCD.setSmallDecimalPoint(False)
        self.coordinatesLCD.setDigitCount(22)
        self.coordinatesLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.coordinatesLCD.setObjectName("coordinatesLCD")
        self.horizontalLayout.addWidget(self.coordinatesLCD)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.consoleEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleEdit.sizePolicy().hasHeightForWidth())
        self.consoleEdit.setSizePolicy(sizePolicy)
        self.consoleEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.consoleEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.consoleEdit.setUndoRedoEnabled(False)
        self.consoleEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.consoleEdit.setCenterOnScroll(True)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.StartExecutionButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartExecutionButton.setObjectName("StartExecutionButton")
        self.verticalLayout_2.addWidget(self.StartExecutionButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 484, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuProgram = QtWidgets.QMenu(self.menuBar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_program = QtWidgets.QAction(MainWindow)
        self.actionLoad_program.setObjectName("actionLoad_program")
        self.actionSave_program = QtWidgets.QAction(MainWindow)
        self.actionSave_program.setObjectName("actionSave_program")
        self.actionUsage = QtWidgets.QAction(MainWindow)
        self.actionUsage.setObjectName("actionUsage")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.menuProgram.addAction(self.actionLoad_program)
        self.menuProgram.addAction(self.actionSave_program)
        self.menuHelp.addAction(self.actionUsage)
        self.menuHelp.addAction(self.actionLicense)
        self.menuBar.addAction(self.menuProgram.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.selectSerialBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectSerialBox.setItemText(0, _translate("MainWindow", "Select serial port"))
        self.connectButton.setText(_translate("MainWindow", "Connect!"))
        self.SingleStepButton.setText(_translate("MainWindow", "Single Step Mode"))
        self.homingButton.setText(_translate("MainWindow", "Start homing cycle"))
        self.unlockButton.setText(_translate("MainWindow", "Unlock!"))
        self.setzeroButton.setText(_translate("MainWindow", "Go to central position"))
        self.addposButton.setText(_translate("MainWindow", "Add  position to queue"))
        self.ramanFilename.setText(_translate("MainWindow", "raman_filename"))
        self.ramanButton.setText(_translate("MainWindow", "Add Raman to queue"))
        self.addCircleButton.setText(_translate("MainWindow", "Add Circle"))
        self.StopExecutionButton.setText(_translate("MainWindow", "STOP"))
        self.stateLabel.setText(_translate("MainWindow", "State"))
        self.StartExecutionButton.setText(_translate("MainWindow", "Start!"))
        self.menuProgram.setTitle(_translate("MainWindow", "Program"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad_program.setText(_translate("MainWindow", "Load program"))
        self.actionSave_program.setText(_translate("MainWindow", "Save program"))
        self.actionUsage.setText(_translate("MainWindow", "Usage"))
        self.actionLicense.setText(_translate("MainWindow", "License"))

