# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 455)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectSerialBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectSerialBox.sizePolicy().hasHeightForWidth())
        self.selectSerialBox.setSizePolicy(sizePolicy)
        self.selectSerialBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selectSerialBox.setEditable(False)
        self.selectSerialBox.setObjectName("selectSerialBox")
        self.selectSerialBox.addItem("")
        self.horizontalLayout_2.addWidget(self.selectSerialBox)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        self.connectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.setzeroButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setzeroButton.sizePolicy().hasHeightForWidth())
        self.setzeroButton.setSizePolicy(sizePolicy)
        self.setzeroButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setzeroButton.setObjectName("setzeroButton")
        self.gridLayout_2.addWidget(self.setzeroButton, 1, 0, 1, 1)
        self.SingleStepButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SingleStepButton.sizePolicy().hasHeightForWidth())
        self.SingleStepButton.setSizePolicy(sizePolicy)
        self.SingleStepButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SingleStepButton.setCheckable(True)
        self.SingleStepButton.setObjectName("SingleStepButton")
        self.gridLayout_2.addWidget(self.SingleStepButton, 0, 0, 1, 1)
        self.homingButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homingButton.sizePolicy().hasHeightForWidth())
        self.homingButton.setSizePolicy(sizePolicy)
        self.homingButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homingButton.setObjectName("homingButton")
        self.gridLayout_2.addWidget(self.homingButton, 0, 1, 1, 1)
        self.unlockButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unlockButton.sizePolicy().hasHeightForWidth())
        self.unlockButton.setSizePolicy(sizePolicy)
        self.unlockButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.unlockButton.setObjectName("unlockButton")
        self.gridLayout_2.addWidget(self.unlockButton, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.addposButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addposButton.sizePolicy().hasHeightForWidth())
        self.addposButton.setSizePolicy(sizePolicy)
        self.addposButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addposButton.setAutoFillBackground(False)
        self.addposButton.setObjectName("addposButton")
        self.verticalLayout.addWidget(self.addposButton)
        self.ramanFilename = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramanFilename.sizePolicy().hasHeightForWidth())
        self.ramanFilename.setSizePolicy(sizePolicy)
        self.ramanFilename.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ramanFilename.setObjectName("ramanFilename")
        self.verticalLayout.addWidget(self.ramanFilename)
        self.ramanButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ramanButton.sizePolicy().hasHeightForWidth())
        self.ramanButton.setSizePolicy(sizePolicy)
        self.ramanButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ramanButton.setObjectName("ramanButton")
        self.verticalLayout.addWidget(self.ramanButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.circlePointsBox = QtWidgets.QSpinBox(self.centralwidget)
        self.circlePointsBox.setMinimum(2)
        self.circlePointsBox.setObjectName("circlePointsBox")
        self.horizontalLayout_3.addWidget(self.circlePointsBox)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.radiusBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.radiusBox.setMinimum(0.0)
        self.radiusBox.setMaximum(5.0)
        self.radiusBox.setSingleStep(0.01)
        self.radiusBox.setProperty("value", 0.01)
        self.radiusBox.setObjectName("radiusBox")
        self.horizontalLayout_3.addWidget(self.radiusBox)
        self.addCircleButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCircleButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addCircleButton.setObjectName("addCircleButton")
        self.horizontalLayout_3.addWidget(self.addCircleButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.topLeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.topLeftButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.topLeftButton.setObjectName("topLeftButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.topLeftButton)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.xresBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.xresBox.setMaximum(5.0)
        self.xresBox.setSingleStep(0.1)
        self.xresBox.setProperty("value", 0.1)
        self.xresBox.setObjectName("xresBox")
        self.horizontalLayout_5.addWidget(self.xresBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.yresBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.yresBox.setMaximum(5.0)
        self.yresBox.setSingleStep(0.1)
        self.yresBox.setProperty("value", 0.1)
        self.yresBox.setObjectName("yresBox")
        self.horizontalLayout_5.addWidget(self.yresBox)
        self.AFcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.AFcheckBox.setObjectName("AFcheckBox")
        self.horizontalLayout_5.addWidget(self.AFcheckBox)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.botRightButton = QtWidgets.QPushButton(self.centralwidget)
        self.botRightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.botRightButton.setObjectName("botRightButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.botRightButton)
        self.mapButton = QtWidgets.QPushButton(self.centralwidget)
        self.mapButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mapButton.setObjectName("mapButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mapButton)
        self.verticalLayout.addLayout(self.formLayout)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.AFButton = QtWidgets.QPushButton(self.centralwidget)
        self.AFButton.setObjectName("AFButton")
        self.horizontalLayout_8.addWidget(self.AFButton)
        self.focusModeBox = QtWidgets.QComboBox(self.centralwidget)
        self.focusModeBox.setEditable(False)
        self.focusModeBox.setCurrentText("Mode")
        self.focusModeBox.setObjectName("focusModeBox")
        self.horizontalLayout_8.addWidget(self.focusModeBox)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.MinFocusSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.MinFocusSpinBox.setMinimum(-20.0)
        self.MinFocusSpinBox.setMaximum(20.0)
        self.MinFocusSpinBox.setProperty("value", -2.0)
        self.MinFocusSpinBox.setObjectName("MinFocusSpinBox")
        self.horizontalLayout_8.addWidget(self.MinFocusSpinBox)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.MaxFocusSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.MaxFocusSpinBox.setMaximum(20.0)
        self.MaxFocusSpinBox.setProperty("value", 2.0)
        self.MaxFocusSpinBox.setObjectName("MaxFocusSpinBox")
        self.horizontalLayout_8.addWidget(self.MaxFocusSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.LEDButton = QtWidgets.QPushButton(self.centralwidget)
        self.LEDButton.setObjectName("LEDButton")
        self.verticalLayout.addWidget(self.LEDButton)
        spacerItem = QtWidgets.QSpacerItem(13, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.StopExecutionButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.StopExecutionButton.sizePolicy().hasHeightForWidth())
        self.StopExecutionButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.StopExecutionButton.setFont(font)
        self.StopExecutionButton.setObjectName("StopExecutionButton")
        self.verticalLayout.addWidget(self.StopExecutionButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stateLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stateLabel.setFont(font)
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout.addWidget(self.stateLabel)
        self.coordinatesLCD = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinatesLCD.sizePolicy().hasHeightForWidth())
        self.coordinatesLCD.setSizePolicy(sizePolicy)
        self.coordinatesLCD.setFrameShape(QtWidgets.QFrame.Box)
        self.coordinatesLCD.setSmallDecimalPoint(False)
        self.coordinatesLCD.setDigitCount(22)
        self.coordinatesLCD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.coordinatesLCD.setObjectName("coordinatesLCD")
        self.horizontalLayout.addWidget(self.coordinatesLCD)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropOverwriteMode(False)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.consoleEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleEdit.sizePolicy().hasHeightForWidth())
        self.consoleEdit.setSizePolicy(sizePolicy)
        self.consoleEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.consoleEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.consoleEdit.setUndoRedoEnabled(False)
        self.consoleEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.consoleEdit.setCenterOnScroll(True)
        self.consoleEdit.setObjectName("consoleEdit")
        self.verticalLayout_2.addWidget(self.consoleEdit)
        self.StartExecutionButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartExecutionButton.setObjectName("StartExecutionButton")
        self.verticalLayout_2.addWidget(self.StartExecutionButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_6.addWidget(self.stopButton)
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout_6.addWidget(self.pauseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 559, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuProgram = QtWidgets.QMenu(self.menuBar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_program = QtWidgets.QAction(MainWindow)
        self.actionLoad_program.setObjectName("actionLoad_program")
        self.actionSave_program = QtWidgets.QAction(MainWindow)
        self.actionSave_program.setObjectName("actionSave_program")
        self.actionUsage = QtWidgets.QAction(MainWindow)
        self.actionUsage.setObjectName("actionUsage")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.menuProgram.addAction(self.actionLoad_program)
        self.menuProgram.addAction(self.actionSave_program)
        self.menuHelp.addAction(self.actionUsage)
        self.menuHelp.addAction(self.actionLicense)
        self.menuBar.addAction(self.menuProgram.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.selectSerialBox.setCurrentIndex(0)
        self.focusModeBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectSerialBox.setItemText(0, _translate("MainWindow", "Select serial port"))
        self.connectButton.setText(_translate("MainWindow", "Connect!"))
        self.setzeroButton.setText(_translate("MainWindow", "Go to central position"))
        self.SingleStepButton.setText(_translate("MainWindow", "Single Step Mode"))
        self.homingButton.setText(_translate("MainWindow", "Start homing cycle"))
        self.unlockButton.setText(_translate("MainWindow", "Unlock!"))
        self.addposButton.setText(_translate("MainWindow", "Add  position to queue"))
        self.ramanFilename.setText(_translate("MainWindow", "raman_filename"))
        self.ramanButton.setText(_translate("MainWindow", "Add Raman to queue"))
        self.label_3.setText(_translate("MainWindow", "points:"))
        self.circlePointsBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Number of points to capture</p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "rad:"))
        self.radiusBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Radius</p></body></html>"))
        self.addCircleButton.setText(_translate("MainWindow", "Add Circle"))
        self.topLeftButton.setText(_translate("MainWindow", "Corner 1"))
        self.label.setText(_translate("MainWindow", "dx:"))
        self.label_2.setText(_translate("MainWindow", "dy:"))
        self.AFcheckBox.setText(_translate("MainWindow", "AF"))
        self.botRightButton.setText(_translate("MainWindow", "Corner 2"))
        self.mapButton.setText(_translate("MainWindow", "Add mapping"))
        self.AFButton.setText(_translate("MainWindow", "Focus"))
        self.label_5.setText(_translate("MainWindow", "min"))
        self.label_6.setText(_translate("MainWindow", "max"))
        self.LEDButton.setText(_translate("MainWindow", "Toggle LED"))
        self.StopExecutionButton.setText(_translate("MainWindow", "RESET"))
        self.stateLabel.setText(_translate("MainWindow", "State"))
        self.StartExecutionButton.setText(_translate("MainWindow", "Start!"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.menuProgram.setTitle(_translate("MainWindow", "Program"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionLoad_program.setText(_translate("MainWindow", "Load program"))
        self.actionSave_program.setText(_translate("MainWindow", "Save program"))
        self.actionUsage.setText(_translate("MainWindow", "Usage"))
        self.actionLicense.setText(_translate("MainWindow", "License"))

