# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mapdesign.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider.sizePolicy().hasHeightForWidth())
        self.slider.setSizePolicy(sizePolicy)
        self.slider.setMinimumSize(QtCore.QSize(132, 0))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout.addWidget(self.slider)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.freqEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freqEdit.sizePolicy().hasHeightForWidth())
        self.freqEdit.setSizePolicy(sizePolicy)
        self.freqEdit.setObjectName("freqEdit")
        self.horizontalLayout.addWidget(self.freqEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.TriangCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.TriangCheckBox.setObjectName("TriangCheckBox")
        self.horizontalLayout_2.addWidget(self.TriangCheckBox)
        self.TriangSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.TriangSpinBox.setMinimum(1)
        self.TriangSpinBox.setMaximum(4)
        self.TriangSpinBox.setObjectName("TriangSpinBox")
        self.horizontalLayout_2.addWidget(self.TriangSpinBox)
        self.interpcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpcheckBox.sizePolicy().hasHeightForWidth())
        self.interpcheckBox.setSizePolicy(sizePolicy)
        self.interpcheckBox.setObjectName("interpcheckBox")
        self.horizontalLayout_2.addWidget(self.interpcheckBox)
        self.methodBox = QtWidgets.QComboBox(self.centralwidget)
        self.methodBox.setObjectName("methodBox")
        self.methodBox.addItem("")
        self.methodBox.addItem("")
        self.horizontalLayout_2.addWidget(self.methodBox)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.dxSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dxSpinBox.sizePolicy().hasHeightForWidth())
        self.dxSpinBox.setSizePolicy(sizePolicy)
        self.dxSpinBox.setDecimals(3)
        self.dxSpinBox.setMinimum(0.001)
        self.dxSpinBox.setMaximum(5.0)
        self.dxSpinBox.setSingleStep(0.001)
        self.dxSpinBox.setObjectName("dxSpinBox")
        self.horizontalLayout_2.addWidget(self.dxSpinBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.orderBox = QtWidgets.QSpinBox(self.centralwidget)
        self.orderBox.setMinimum(1)
        self.orderBox.setMaximum(5)
        self.orderBox.setObjectName("orderBox")
        self.horizontalLayout_2.addWidget(self.orderBox)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.smoothSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.smoothSpinBox.setMaximum(5.0)
        self.smoothSpinBox.setSingleStep(0.05)
        self.smoothSpinBox.setObjectName("smoothSpinBox")
        self.horizontalLayout_2.addWidget(self.smoothSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pltWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pltWidget.sizePolicy().hasHeightForWidth())
        self.pltWidget.setSizePolicy(sizePolicy)
        self.pltWidget.setObjectName("pltWidget")
        self.verticalLayout.addWidget(self.pltWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 681, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionExport_to_Gwyddion = QtWidgets.QAction(MainWindow)
        self.actionExport_to_Gwyddion.setObjectName("actionExport_to_Gwyddion")
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionExport_to_Gwyddion)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ṽ, cm^-1"))
        self.TriangCheckBox.setText(_translate("MainWindow", "Triangulate:"))
        self.interpcheckBox.setText(_translate("MainWindow", "Interpolate:"))
        self.methodBox.setItemText(0, _translate("MainWindow", "Clough-Tocher"))
        self.methodBox.setItemText(1, _translate("MainWindow", "Spline"))
        self.label.setText(_translate("MainWindow", "Step:"))
        self.label_2.setText(_translate("MainWindow", "Order"))
        self.label_5.setText(_translate("MainWindow", "Smooth:"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionOpen_Folder.setText(_translate("MainWindow", "&Open Folder"))
        self.actionExport_to_Gwyddion.setText(_translate("MainWindow", "Export to Gwyddion"))

